project:
  type: website
  output-dir: docs

website:
  title: "Teach Me More"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - photos.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    embed-resources: true

editor: visual

